local settlements_to_disable = {
    "wh2_main_atalan_mountains_vulture_mountain",
    "wh2_main_vor_cobra_pass_vulture_mountain",
    "wh2_main_southlands_worlds_edge_mountains_karak_zorn",
    "wh2_main_vor_southlands_world_edge_mountains_karak_zorn",
    "wh2_main_southlands_worlds_edge_mountains_mount_arachnos",
    "wh2_main_vor_southlands_world_edge_mountains_mount_arachnos",
    "wh2_main_charnel_valley_granite_massif",
    "wh_main_blightwater_deff_gorge",
    "wh_main_blightwater_karak_azgal",
    "wh_main_blightwater_misty_mountain",
    "wh2_main_the_plain_of_bones_ash_ridge_mountains",
    "wh2_main_the_wolf_lands_crookback_mountain",
    "wh2_main_the_wolf_lands_mount_silverspear",
    "wh_main_the_silver_road_karaz_a_karak",
    "wh_main_zhufbar_zhufbar",
    "wh_main_rib_peaks_mount_gunbad",
    "wh_main_peak_pass_karak_kadrin",
    "wh_main_northern_worlds_edge_mountains_karak_ungor",
    "wh2_main_northern_worlds_edge_mountains_karak_raziak",
    "wh_main_gianthome_mountains_kraka_drak",
    "wh_main_gianthome_mountains_khazid_bordkarag",
    "wh_main_southern_grey_mountains_karak_azgaraz",
    "wh_main_southern_grey_mountains_karak_norn",
    "wh_main_southern_grey_mountains_grimhold",
    "wh2_main_fort_helmgart",
    "wh_main_northern_grey_mountains_karak_ziflin",
    "wh_main_northern_grey_mountains_grung_zint",
    "wh_main_western_badlands_ekrund",
    "wh_main_eastern_badlands_karak_eight_peaks",
}

return settlements_to_disable